#name: edgeTestCases.function-sql
functions:
  - name: 'simple_sql'
    handler: 'select *'
#  - name: 'simple_sql1'
#    handler: 'select *'
#  - name: 'simple_sql2'
#    handler: 'select *'
#  - name: 'simple_sql3'
#    handler: 'select *'
#  - name: 'simple_sql4'
#    handler: 'select *'
#  - name: 'simple_sql5'
#    handler: 'select *'
#  - name: 'simple_sql6'
#    handler: 'select *'
