#name: function-manager
hub:
  address: tcp://localhub:8963
  username: test
  password: test

rules:
  - clientid: rule-e1iluuac1
    subscribe:
      topic: multi/test
    function:
      name: filter
    publish:
      topic: result/sql
  - clientid: rule-e1iluuac2
    subscribe:
      topic: multi/test
      qos: 1
    function:
      name: sayhi
    publish:
      topic: result/python
      qos: 1
  - clientid: rule-e1iluuac3
    subscribe:
      topic: chain/test/2
    function:
      name: simple_sql
    publish:
      topic: redirect_to_function
  - clientid: rule-e1iluuac4
    subscribe:
      topic: redirect_to_function
    function:
      name: simple_python
    publish:
      topic: chain/test/3
  - clientid: rule-e1iluuac5
    subscribe:
      topic: across/result
    function:
      name: simple_sql
    publish:
      topic: across/back
  - clientid: rule-e1iluuac6
    subscribe:
      topic: qos/at_most_once_function
      qos: 0
    function:
      name: simple_sql
    publish:
      topic: qos/result/function/at_least_once
      qos: 1
  - clientid: rule-e1iluuac7
    subscribe:
      topic: plus/wildcard/+
    function:
      name: simple_sql
    publish:
      topic: result/wildcard/plus
  - clientid: rule-e1iluuac8
    subscribe:
      topic: selectMany
    function:
      name: complex_select
    publish:
      topic: result/select/many
  - clientid: rule-e1iluuac9
    subscribe:
      topic: selectFunctions
    function:
      name: select_functions
    publish:
      topic: result/select/function
  - clientid: rule-e1iluuac10
    subscribe:
      topic: custom/functions
    function:
      name: custom_functions_1
    publish:
      topic: result/custom/function
  - clientid: rule-e1iluuac11
    subscribe:
      topic: custom/functions2
    function:
      name: custom_functions_2
    publish:
      topic: result/custom/function2
  - clientid: rule-e1iluuac12
    subscribe:
      topic: where/test
    function:
      name: where_test1
    publish:
      topic: result/where/test1
  - clientid: rule-e1iluuac13
    subscribe:
      topic: where/test
    function:
      name: where_test2
    publish:
      topic: result/where/test2
  - clientid: rule-e1iluuac14
    subscribe:
      topic: nestmsg/test
    function:
      name: nestmsg
    publish:
      topic: result/nestmsg
  - clientid: rule-e1iluuac15
    subscribe:
      topic: python/function/test
      qos: 1
    function:
      name: sayhi
    publish:
      topic: python/function/result
  - clientid: rule-e1iluuac16
    subscribe:
      topic: python/function/test
    function:
      name: sayhi_serial
    publish:
      topic: python/function/serial/result

functions:
  - name: 'simple_sql'
    service: function-simple_sql
  - name: 'filter'
    service: function-filter
  - name: 'complex_select'
    service: function-complex_select
  - name: 'select_functions'
    service: function-select_functions
  - name: 'custom_functions_1'
    service: function-custom_functions_1
  - name: 'custom_functions_2'
    service: function-custom_functions_2
  - name: 'where_test1'
    service: function-where_test1
    instance:
      max: 5
  - name: 'where_test2'
    service: function-where_test2
    instance:
      max: 5
  - name: 'nestmsg'
    service: function-nestmsg
  - name: 'simple_python'
    service: function-simple_python
  - name: 'sayhi'
    service: function-sayhi
    instance:
      min: 1
      max: 3
      timeout: '10s'
      memory:
        high: '8m'
        max: '10m'
      cpu:
        period: 1000000
        max: 500000
      pids:
        max: 2
  - name: 'sayhi_serial'
    service: function-sayhi_serial
    env:
      USER_NAME: 'zm'
    instance:
      min: 0
      max: 1
      timeout: '10s'
      memory:
        high: '8m'
        max: '10m'
      cpu:
        period: 1000000
        max: 500000
      pids:
        max: 2

logger:
  path: var/log/baetyl/baetyl_function.log
  console: true
  level: "debug"
