version: V1
services:
  # localHub
  - name: openedge_hub
    image: hub.baidubce.com/openedgedev/openedge-hub:latest
    replica: 1
    ports:
      - 8963:8963
      - 8964:8964
      - 8965:8965
      - 8966:8966
    mounts:
      - name: localhub-conf
        path: etc/openedge
        readonly: true
      - name: localhub-cert
        path: var/db/openedge/cert
        readonly: true
      - name: localhub-data
        path: var/db/openedge/data
      - name: localhub-log
        path: var/log/openedge
    replica: 1

  # localHub as remote
  - name: remote_hub
    image: hub.baidubce.com/openedgedev/openedge-hub:latest
    replica: 1
    ports:
      - 7963:7963
    mounts:
      - name: remotehub-conf
        path: etc/openedge
        readonly: true
      - name: remotehub-data
        path: var/db/openedge/data
      - name: remotehub-log
        path: var/log/openedge
    replica: 1

  # remote
  - name: remote-inner
    image: hub.baidubce.com/openedgedev/openedge-remote-mqtt:latest
    replica: 1
    mounts:
      - name: remote-inner-conf
        path: etc/openedge
        readonly: true
      - name: remote-inner-log
        path: var/log/openedge

  - name: remote-nosubauth
    image: hub.baidubce.com/openedgedev/openedge-remote-mqtt:latest
    replica: 1
    mounts:
      - name: remote-nosubauth-conf
        path: etc/openedge
        readonly: true
      - name: remote-nosubauth-log
        path: var/log/openedge

  #functions
  - name: function-manager
    image: hub.baidubce.com/openedgedev/openedge-function-manager:latest
    replica: 1
    mounts:
      - name: function-manager-conf
        path: etc/openedge
        readonly: true
      - name: function-manager-log
        path: var/log/openedge

  #python functions
  - name: function-sayhi
    image: hub.baidubce.com/openedgedev/openedge-function-python27:latest
    replnosubica: 0
    env:
      USER_NAME: 'zm'
    mounts:
      - name: function-sayhi-conf
        path: etc/openedge
        readonly: true
      - name: function-python-code
        path: var/db/openedge/function
        readonly: true
    resources:
      memory:
        limit: '500m'
        swap: '1g'
      #cpu:
        #cpus: 1.5 
        #setcpus: 0-2
      pids:
        limit: 40
  - name: function-sayhi_serial
    image: hub.baidubce.com/openedgedev/openedge-function-python27:latest
    replica: 0
    mounts:
      - name: function-sayhi_serial-conf
        path: etc/openedge
        readonly: true
      - name: function-python-code
        path: var/db/openedge/function
        readonly: true
  - name: function-simple_python
    image: hub.baidubce.com/openedgedev/openedge-function-python27:latest
    replica: 0
    mounts:
      - name: function-simple_python-conf
        path: etc/openedge
        readonly: true
      - name: function-python-code
        path: var/db/openedge/function
        readonly: true

#sql functions
  - name: function-complex_select
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 0
    mounts:
      - name: function-complex_select-conf
        path: etc/openedge
        readonly: true
  - name: function-custom_functions_1
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 0
    mounts:
      - name: function-custom_functions_1-conf
        path: etc/openedge
        readonly: true
  - name: function-custom_functions_2
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 0
    mounts:
      - name: function-custom_functions_2-conf
        path: etc/openedge
        readonly: true
  - name: function-filter
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 1
    mounts:
      - name: function-filter--conf
        path: etc/openedge
        readonly: true
  - name: function-nestmsg
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 2
    mounts:
      - name: function-nestmsg-conf
        path: etc/openedge
        readonly: true
  - name: function-select_functions
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 0
    mounts:
      - name: function-select_functions-conf
        path: etc/openedge
        readonly: true
  - name: function-simple_sql
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 1
    mounts:
      - name: function-simple_sql-conf
        path: etc/openedge
        readonly: true
  - name: function-where_test1
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 0
    mounts:
      - name: function-where_test1-conf
        path: etc/openedge
        readonly: true
  - name: function-where_test2
    image: hub.baidubce.com/openedgedev/openedge-function-sql:latest
    replica: 0
    mounts:
      - name: function-where_test2-conf
        path: etc/openedge

volumes:
  # hub
  - name: localhub-conf
    path: var/db/openedge/localhub-conf
  - name: localhub-data
    path: var/db/data/openedge/localhub-data
  - name: localhub-cert
    path: var/db/openedge/localhub-conf/cert
  - name: localhub-log
    path: var/db/log/openedge/localhub-log

  - name: remotehub-conf
    path: var/db/openedge/remotehub-conf
  - name: remotehub-data
    path: var/db/data/openedge/remotehub-data
  - name: remotehub-log
    path: var/db/log/openedge/remotehub-log

  # remote
  - name: remote-inner-conf
    path: var/db/openedge/remote-inner-conf
  - name: remote-inner-log
    path: var/db/log/openedge/remote-inner-log

  - name: remote-nosubauth-conf
    path: var/db/openedge/remote-nosubauth-conf
  - name: remote-nosubauth-log
    path: var/db/log/openedge/remote-iothub-log

  # function
  - name: function-manager-conf
    path: var/db/openedge/function-manager-conf
  - name: function-manager-log
    path: var/db/log/openedge/function-manager-log

  # sql
  - name: function-simple_sql-conf
    path: var/db/openedge/function-sql-conf/function-simple_sql-conf
  - name: function-filter--conf
    path: var/db/openedge/function-sql-conf/function-filter--conf
  - name: function-complex_select-conf
    path: var/db/openedge/function-sql-conf/function-complex_select-conf
  - name: function-custom_functions_1-conf
    path: var/db/openedge/function-sql-conf/function-custom_functions_1-conf
  - name: function-custom_functions_2-conf
    path: var/db/openedge/function-sql-conf/function-custom_functions_2-conf
  - name: function-nestmsg-conf
    path: var/db/openedge/function-sql-conf/function-nestmsg-conf
  - name: function-select_functions-conf
    path: var/db/openedge/function-sql-conf/function-select_functions-conf
  - name: function-where_test1-conf
    path: var/db/openedge/function-sql-conf/function-where_test1-conf
  - name: function-where_test2-conf
    path: var/db/openedge/function-sql-conf/function-where_test2-conf

  # python
  - name: function-sayhi-conf
    path: var/db/openedge/function-sayhi-conf
  - name: function-sayhi_serial-conf
    path: var/db/openedge/function-sayhi_serial-conf
  - name: function-simple_python-conf
    path: var/db/openedge/function-simple_python-conf
  - name: function-python-code
    path: var/db/openedge/function-python-code
