name: openedge_hub
listen:
  - tcp://:7963

message:
  length:
    max: '32k'
  ingress:
    qos0:
      persist: false
      buffer: 
        size: 10000
    qos1:
      buffer:
        size: 100
      batch:
        max: 50
      cleanup:
        retention: '2m'
  egress:
    qos0:
      buffer:
        size: 1000
    qos1:
      buffer:
        size: 5
      batch:
        max: 10
      retry:
        interval: '10s'
      offset:
        buffer:
          size: 1000
        batch:
          max: 100
principals:
  - username: 'remotetest'
    password: 'remotetest'
    permissions:
      - action: 'pub'
        permit: ['#']
      - action: 'sub'
        permit: ['#']
  - username: 'remoteauth'
    password: 'remoteauth'
    permissions:
      - action: 'pub'
        permit: ['remote/#']
      - action: 'sub'
        permit: ['remote/#']

logger:
  path: var/log/openedge/remote_hub.log
  console: true
  level: "debug"
